### Requerimientos
Para crear el ambiente correr en la consola
```
$ python3 -m venv algebra-lineal-with-python
$ algebra-lineal-with-python/bin/activate
$ pip3 install numpy
```

In [12]:
import numpy as np

### Creando escalares

In [7]:
print("Creando escalares")
a = 2 # Escalar tipo 'Int'
b = 3.1416 # Escalar tipo 'Float'
print(a)
print(b)

Creando escalares
2
3.1416


### Creando vectores

In [9]:
print("Creando vectores")

Creando vectores


#### 1.- Convirtiendo una lista Python en un NumPy Array

In [14]:
a_lista = [1,2,3,4]
a_array = np.array(a_lista)
print(a_array)
print(a_lista)

[1 2 3 4]


#### 2.- Creandolo directamente en NumPy

In [16]:
b_array = np.array([5,6,7])
print(a_array)

[1 2 3 4]


### Creando matrices

In [19]:
print("Creando matrices")
print("Forma 1")
A = np.matrix([
    [3, 5],
    [1, 0]
])
print(A)

Creando matrices
Forma 1
[[3 5]
 [1 0]]


In [20]:
print("Forma 2")
matrix_object = np.mat([[1, 2],[1, 2],[1, 2]])
print(matrix_object)

Forma 2
[[1 2]
 [1 2]
 [1 2]]


In [21]:
print("Forma 3")
matrix = np.array([[1, 2],[3, 4],[5, 6]])
print(matrix)

Forma 3
[[1 2]
 [3 4]
 [5 6]]


#### Podemos 'capturar' un determinado valor seleccionando su posición dentro de la matriz

In [ ]:
print(matrix[2][0]) ##Devuelve: 5

### Operaciones con vectores

In [ ]:
print("Operando con vectores"

#### Suma de vectores

In [22]:
print("Suma de vectores")
v = np.array([3, 7])
u = np.array([2, 2])
print(v + u)

Suma de vectores
[5 9]


#### Escalar por Vector

In [23]:
print("Escalar por Vector")
m = np.array([4,1,7])
e = 3
mul = e * m
print(mul)

Escalar por Vector
[12  3 21]


#### Producto Punto

In [24]:
print("Producto Punto")
print("Forma 1")
v = np.array([3, 7])
u = np.array([2, 2])
mul = np.dot(v,u)
print(mul)

Producto Punto
Forma 1
20


In [25]:
print("Forma 2")
v = np.array([3, 7])
u = np.array([2, 2])
print(v.dot(u))

Forma 2
20


#### Norma o Magnitud de un vector

In [26]:
print("Norma o Magnitud de un vector")
v = np.array([3, 2, 7])
print(np.linalg.norm(v))

Norma o Magnitud de un vector
7.874007874011811


#### Vector unitario

In [27]:
print("Vector unitario")
def unit_vector(v):
    return v / np.linalg.norm(v)

u = np.array([3, 6, 4])
print(unit_vector(u))

Vector unitario
[0.38411064 0.76822128 0.51214752]


#### Ángulos entre vectores

In [28]:
print("Ángulos entre vectores")
def angle_between(v1, v2):
    dot_pr = v1.dot(v2)
    norms = np.linalg.norm(v1) * np.linalg.norm(v2)
    return np.rad2deg(np.arccos(dot_pr / norms))

v = np.array([1, 4, 5])
u = np.array([2, 1, 5])
print(angle_between(v, u))

Ángulos entre vectores
29.152519407030084


### Operaciones con matrives

#### Suma de matrices

In [29]:
print("Suma de matrices")
A = np.matrix([
    [3, 5],
    [1, 0]
])
B = np.matrix([
    [2, -3],
    [1, 2]
])
print(A + B)

Suma de matrices
[[5 2]
 [2 2]]


#### Escalar por matriz

In [30]:
print("Escalar por matriz")
A = np.matrix([
    [3, 5],
    [1, 0]
])
print(2 * A)

Escalar por matriz
[[ 6 10]
 [ 2  0]]


#### Multiplicación de matrices

In [31]:
print("Multiplicación de matrices")
A = np.matrix([
    [3, 4],
    [1, 0]
])
B = np.matrix([
    [2, 2],
    [1, 2]
])
print(A.dot(B))

Multiplicación de matrices
[[10 14]
 [ 2  2]]


### Producto Hadamard

In [35]:
print("Producto Hadamard")
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


Producto Hadamard


#### La multiplicación se puede realizar con multiply de NumPy y también de manera directa usando la multiplicación Python (*)


In [37]:
print("Forma 1")
mul = np.multiply(a,b)
##Imprimimos mul para ver la matriz respuesta
print(mul) ##Devuelve: array([[ 5, 12],[21, 32]])


Forma 1
[[ 5 12]
 [21 32]]


In [38]:
print("Forma 2")
print(a*b)

Forma 2
[[ 5 12]
 [21 32]]


## Tipos de matrices

### Matriz Identidad

In [39]:
print("Matriz Identidad")

Matriz Identidad


#### Declaramos la matriz identidad con identity de Numpy

In [40]:
print("Forma 1")
m_identidad = np.identity(5) #Devuelve la matriz identidad de tamaño 5x5
print(m_identidad)

Forma 1
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
print("Forma 2")
A = np.eye(3)
print(A)

Forma 2
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
print("Matriz identidad de tipo float")
B = np.eye(2, dtype = float)
print(B)

Matriz identidad de tipo float
[[1. 0.]
 [0. 1.]]


In [44]:
print("Especificando número de filas y columnas")
C= np.eye(4, 5)
print(C)

Especificando número de filas y columnas
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [45]:
C = np.eye(4, 5, k = -1)

## Matriz Transpuesta

In [50]:
print("Matriz Transpuesta")

Matriz Transpuesta


In [51]:
print("Matriz 1")
A = np.matrix([
    [3, 4],
    [1, 0]
])
print(A.T)

Matriz 1
[[3 1]
 [4 0]]


In [52]:
print("Matriz 2")
A = np.array([[1, 2], [3, 4], [5, 6]])
A_t = A.T
print(A_t)

Matriz 2
[[1 3 5]
 [2 4 6]]


## Determinante

In [53]:
print("Determinante")
A = np.matrix([
    [3, 2],
    [1, 6]
])
print(np.linalg.det(A))

Determinante
16.000000000000007


## Matriz Inversa

In [55]:
print("Matriz Inversa")
#Declaramos la matriz A
A = np.array(([1,3,3],[1,4,3],[1,3,4]))
#Invertimos la matriz usando NumPy
A_inv = np.linalg.inv(A)
#Comprobamos la matriz inversa
print(A_inv)
#Devuelve la matriz inversa de A:

Matriz Inversa
[[ 7. -3. -3.]
 [-1.  1.  0.]
 [-1.  0.  1.]]


In [56]:
print("Segunda matriz inversa")
A = np.matrix([
    [4, 3],
    [5, 4]
])
print(np.linalg.inv(A))

Segunda matriz inversa
[[ 4. -3.]
 [-5.  4.]]
